### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ThomasGoerttler** [blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks#3]
Currently the scale of the images varies.
This has to be corrected.

**Comment by ThomasGoerttler** [comment]
align the image of the tab view. The source files have different sizes -> the scale differently. However a single image spot should stay the same (this is almost perfect in the second tab view) -> so the change has to happen in the files: https://github.com/blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/blob/main/assets/img/2022-12-01-how-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/Figure2.PNG and https://github.com/blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/blob/main/assets/img/2022-12-01-how-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/Figure3.PNG

**Comment by Ch-1212** [comment]
I changed the file (Figure3) to match the figure2 and pushed the changes to my fork of the repo. Unfortunately, I can't see if that worked. I tried to do a pull request to the original repo and it said it had worked but I can't find the changes here and in my fork it still says that I am one commit ahead.

**Comment by Ch-1212** [comment]
I tried to improve that. It is definitely better but not perfect...
