### ISSUE TITLE
HTML figures

### ISSUE THREAD

**Issue by ThomasGoerttler** [blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks#4]
have to be corrected

**Comment by ThomasGoerttler** [comment]
are now better, but somehow the in-between phase does not work

**Comment by Ch-1212** [comment]
Is the version under posts/<title> the deployed version? Because there I can't see the pictures either? Or is that something else?

**Comment by ThomasGoerttler** [comment]
The deployed version is [here](https://blogosfair.github.io/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks//blog/2022/how-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/)

under _posts/... there is the source-file

**Comment by Ch-1212** [comment]
Ah thanks! 

I don't really see the bug, for me I can see all the pictures... Can you maybe describe it more?

**Comment by ThomasGoerttler** [comment]
Yeah it actually is not a bug anymore ( I fixed the bug).
So this issue can be closed
