### ISSUE TITLE
Lineplot in pure plotly

### ISSUE THREAD

**Issue by ThomasGoerttler** [blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks#5]
currently a static image, but not reason to be so.

**Comment by Ch-1212** [comment]
I would like to change that. Can you recommend to me how to do that? Can you use excel for that?

**Comment by ThomasGoerttler** [comment]
Under https://blogosfair.github.io/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks//blog/2022/distill-example/ it is explained how to inlclude them.
Basically

1. you have to crawl the values of the plot (if they are on a table it is easy, if only in plots we have to take them from the plot).
2. write plotly code to plot the graph
3. export it to html (see under the link above)
4. include it to the posts

**Comment by Ch-1212** [comment]
I would really like to change that but unfortunately I am not able to generate this graph correctly with plotly.
The y-axis is always seperated for the two parts...
![image](https://user-images.githubusercontent.com/75210782/214812760-4db4268c-c70d-4441-99c1-1daae30d1244.png)

This is the code I use:
import pandas as pd
import plotly.express as px
import matplotlib.pylab as plt

df = pd.read_csv('Number_parameters_en2.csv')

df1 = df.melt(id_vars=['#Layers'], var_name='Algorithm')

fig = px.line(df1, x='#Layers', y='value', color='Algorithm', symbol="Algorithm")
fig.update_layout(yaxis_title='#Parameter')
fig.show()

Do you have an idea how to combine the values on the y-axis?

**Comment by ThomasGoerttler** [comment]
without the data it is not possible to help.

**Comment by Ch-1212** [comment]
That is the data
![image](https://user-images.githubusercontent.com/75210782/218149191-199b8c93-1e8b-4267-b629-b792e6f9e252.png)

**Comment by ThomasGoerttler** [comment]
thanks.
just in time :D
For the future: never share data as a screenshot
