### ISSUE TITLE
Different spaces after images/ tab views

### ISSUE THREAD

**Issue by Ch-1212** [blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks#8]
When looking at the preview I find different spaces after the tab view images. After the first one (in Experiments), there is a large space whereas after the second tab view image (CNN) there is no space. 

I would like that to be consistent (taking into account that after the first one a headline follows)

Needs to be changed here:
https://github.com/blogosfair/How-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks/blob/main/_posts/2022-12-01-how-does-the-inductive-bias-influence-the-generalization-capability-of-neural-networks.md

Maybe just take out the space after the first one? I am not sure since this is not the original markdown source file anymore...

**Comment by ThomasGoerttler** [comment]
problem ist that html changes after selecting tabs. In addition it it included as iframe, which cannot have simply different sizes.
I tried different things, but it did not work.
Therefore, I fixed it but not to 600px but to a correct size.
